# K8S Worker Node 3
ansible_host: 10.2.2.7

nic_count: 1
nic1_interface: ens160
nic1_ip_address: 10.2.2.7
nic1_netmask: 255.255.255.0
nic1_gateway: 10.2.2.1

# Ingress VIP (Pair with WN5)
keepalived_router_id: WN3_INGRESS_VIP
vrrp:
  name: VI_INGRESS
  interface: ens160
  vrid: 200
  priority: 140
  auth_pass: ingvip01
  vip: 10.2.2.101/24
