# K8S Worker Node 1
ansible_host: 10.2.2.5

nic_count: 1
nic1_interface: ens160
nic1_ip_address: 10.2.2.5
nic1_netmask: 255.255.255.0
nic1_gateway: 10.2.2.1

# API VIP (Pair with WN2) - MASTER
keepalived_router_id: WN1_API_VIP
vrrp:
  name: VI_API
  interface: ens160
  vrid: 53
  priority: 150
  auth_pass: apivip01
  vip: 10.2.2.253/24
